name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 매일 자정 실행
  workflow_dispatch: # 수동 실행 버튼 활성화
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: aktmdtkd
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          
          # 이미지 생성을 위한 설정들
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_reactions: yes
          plugin_people: yes
          plugin_calendar: yes
          plugin_calendar_limit: 0

          # 저장 경로 (README 코드의 경로와 일치)
          filename: .github/src/metrics.*